export { ingest, UnsupportedScoreError } from './ingest/index.ts'
export { prepare } from './prepare/index.ts'
export type { CleanupReport } from './prepare/index.ts'
export type { Adjustment, AdjustmentKind, Severity } from './prepare/adjustments.ts'
export type { SoloistRegion } from './prepare/soloists.ts'
export type { FormResult } from './prepare/form.ts'
export type {
  Score, Note, Chord, ChordTrack, Instrument, Mark, Quality, Provenance,
} from './core/types.ts'
export { TICKS_PER_QUARTER } from './core/types.ts'
export { degreeOf, intervalsOf, isChordTone, pitchClass } from './core/pitch.ts'
export { instrumentFromTranspose } from './core/instrument.ts'
export { analyse } from './analyse/index.ts'
export type { Analysis, Finding, FindingSpan } from './analyse/index.ts'
export { generateExercises } from './generate/index.ts'
export type { Exercise, ExerciseBar } from './generate/index.ts'
export { exerciseToMusicXml } from './render/musicxml.ts'
export { run, describeFinding } from './pipeline.ts'
export type { FindingView, PipelineResult } from './pipeline.ts'
